In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dfff = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
   ....:                           'foo', 'bar', 'foo', 'foo'],
   ....:                    'B' : ['one', 'one', 'two', 'three',
   ....:                           'two', 'two', 'one', 'three'],
   ....:                    'C' : np.random.randn(8),
   ....:                    'D' : np.random.randn(8)})

In [3]:
dfff

A      B         C         D
0  foo    one -0.093193  0.861379
1  bar    one  1.816625  0.855431
2  foo    two  1.066278 -0.949237
3  bar  three -0.000946  1.216019
4  foo    two  0.980607  0.408805
5  bar    two -1.184853 -0.178715
6  foo    one  1.033761  0.137436
7  foo  three -1.472586 -0.253635

In [4]:
#通过'B'列进行分组，然后求出每个组的元素个数
dfff.groupby('B').size()     

B
one      3
three    2
two      3
dtype: int64

In [5]:
muind = pd.MultiIndex.from_tuples([('a',1),('b',2),('c',3),('a',2),('b',2),('c',3),('a',1),('b',1)],names = ['abc','onetwothree'])

In [6]:
muind

MultiIndex(levels=[['a', 'b', 'c'], [1, 2, 3]],
           labels=[[0, 1, 2, 0, 1, 2, 0, 1], [0, 1, 2, 1, 1, 2, 0, 0]],
           names=['abc', 'onetwothree'])

In [7]:
dfff.index = muind

In [8]:
dfff

A      B         C         D
abc onetwothree                                
a   1            foo    one -0.093193  0.861379
b   2            bar    one  1.816625  0.855431
c   3            foo    two  1.066278 -0.949237
a   2            bar  three -0.000946  1.216019
b   2            foo    two  0.980607  0.408805
c   3            bar    two -1.184853 -0.178715
a   1            foo    one  1.033761  0.137436
b   1            foo  three -1.472586 -0.253635

In [9]:
dfff.index

MultiIndex(levels=[['a', 'b', 'c'], [1, 2, 3]],
           labels=[[0, 1, 2, 0, 1, 2, 0, 1], [0, 1, 2, 1, 1, 2, 0, 0]],
           names=['abc', 'onetwothree'])

In [10]:
#通过层级索引进行分组，然后计算每个分组的元素个数
dfff.groupby(level = 'onetwothree').size()    

onetwothree
1    3
2    3
3    2
dtype: int64

In [11]:
#通过'A'列分组，然后分组聚合：'C'列求最大值，'D'列求最小值
dfff.groupby('A').agg({'C':'max','D':'min'})    

C         D
A                      
bar  1.816625 -0.178715
foo  1.066278 -0.949237

In [12]:
#通过'B'列分组后计算每列的元素个数(不包括NaN值)
dfff.groupby('B').count()  

A  C  D
B             
one    3  3  3
three  2  2  2
two    3  3  3

In [13]:
#通过'B'列分组后计算每列的元素个数(不包括NaN值)且与2进行对比
dfff.groupby('B').count()>2

A      C      D
B                         
one     True   True   True
three  False  False  False
two     True   True   True

In [14]:
#对“B”列的数进行计算个数
ss = dfff['B'].value_counts()

In [15]:
ss

two      3
one      3
three    2
Name: B, dtype: int64

In [16]:
#求出Series中大于2的数值
ss[ss.values>2]

two    3
one    3
Name: B, dtype: int64

In [17]:
#返回布尔类型的数组
ss.values>2

array([ True,  True, False])

In [18]:
#求出'B'列的单一字符出现次数大于2的那几行的数据
dfff[dfff['B'].isin(ss[ss.values>2].index)]

A    B         C         D
abc onetwothree                              
a   1            foo  one -0.093193  0.861379
b   2            bar  one  1.816625  0.855431
c   3            foo  two  1.066278 -0.949237
b   2            foo  two  0.980607  0.408805
c   3            bar  two -1.184853 -0.178715
a   1            foo  one  1.033761  0.137436

In [19]:
#也可以通过'B'列进行分组然后应用函数len()来计算每个分组的大小是否大于2
a = dfff.groupby('B').apply(lambda x:len(x)>2)

In [20]:
a

B
one       True
three    False
two       True
dtype: bool

In [21]:
dfff[dfff['B'].isin(a[a == True].index)]

A    B         C         D
abc onetwothree                              
a   1            foo  one -0.093193  0.861379
b   2            bar  one  1.816625  0.855431
c   3            foo  two  1.066278 -0.949237
b   2            foo  two  0.980607  0.408805
c   3            bar  two -1.184853 -0.178715
a   1            foo  one  1.033761  0.137436

In [22]:
dfff

A      B         C         D
abc onetwothree                                
a   1            foo    one -0.093193  0.861379
b   2            bar    one  1.816625  0.855431
c   3            foo    two  1.066278 -0.949237
a   2            bar  three -0.000946  1.216019
b   2            foo    two  0.980607  0.408805
c   3            bar    two -1.184853 -0.178715
a   1            foo    one  1.033761  0.137436
b   1            foo  three -1.472586 -0.253635

In [23]:
#通过'B'列分组，然后
dfff.groupby('B').shift(1)

A         C         D
abc onetwothree                         
a   1            NaN       NaN       NaN
b   2            foo -0.093193  0.861379
c   3            NaN       NaN       NaN
a   2            NaN       NaN       NaN
b   2            foo  1.066278 -0.949237
c   3            foo  0.980607  0.408805
a   1            bar  1.816625  0.855431
b   1            bar -0.000946  1.216019

In [24]:
dfff.shift(1)

A      B         C         D
abc onetwothree                                
a   1            NaN    NaN       NaN       NaN
b   2            foo    one -0.093193  0.861379
c   3            bar    one  1.816625  0.855431
a   2            foo    two  1.066278 -0.949237
b   2            bar  three -0.000946  1.216019
c   3            foo    two  0.980607  0.408805
a   1            bar    two -1.184853 -0.178715
b   1            foo    one  1.033761  0.137436

In [25]:
dfff['C']=[1,2,3,4,5,6,7,8]

In [26]:
dfff['D'] = [1,2,3,4,5,6,7,8]

In [27]:
dfff

A      B  C  D
abc onetwothree                  
a   1            foo    one  1  1
b   2            bar    one  2  2
c   3            foo    two  3  3
a   2            bar  three  4  4
b   2            foo    two  5  5
c   3            bar    two  6  6
a   1            foo    one  7  7
b   1            foo  three  8  8

In [28]:
dfff.groupby('B').shift(1)

A    C    D
abc onetwothree               
a   1            NaN  NaN  NaN
b   2            foo  1.0  1.0
c   3            NaN  NaN  NaN
a   2            NaN  NaN  NaN
b   2            foo  3.0  3.0
c   3            foo  5.0  5.0
a   1            bar  2.0  2.0
b   1            bar  4.0  4.0

In [29]:
ddef = pd.DataFrame({'A':['人工智能','大数据','h5','人工智能','大数据','h5','大数据','h5','人工智能'],
                    'B':['甲班','乙班','丙班','A班','B班','C班','1班','2班','3班'],
                    'C':['张三','李四','王五','张三','李四','王五','张三','李四','王五'],
                    '分数':[99,80,100,80,69,92,88,98,76],
                    '年龄':[21,22,20,18,19,20,23,22,21]})

In [30]:
ddef

A   B   C   分数  年龄
0  人工智能  甲班  张三   99  21
1   大数据  乙班  李四   80  22
2    h5  丙班  王五  100  20
3  人工智能  A班  张三   80  18
4   大数据  B班  李四   69  19
5    h5  C班  王五   92  20
6   大数据  1班  张三   88  23
7    h5  2班  李四   98  22
8  人工智能  3班  王五   76  21

In [31]:
ddef.rank(method = 'dense')

A    B    C   分数   年龄
0  2.0  9.0  1.0  7.0  4.0
1  3.0  8.0  2.0  3.0  5.0
2  1.0  7.0  3.0  8.0  3.0
3  2.0  4.0  1.0  3.0  1.0
4  3.0  5.0  2.0  1.0  2.0
5  1.0  6.0  3.0  5.0  3.0
6  3.0  1.0  1.0  4.0  6.0
7  1.0  2.0  2.0  6.0  5.0
8  2.0  3.0  3.0  2.0  4.0

In [32]:
ddef.rank(method = 'min')

A    B    C   分数   年龄
0  4.0  9.0  1.0  8.0  5.0
1  7.0  8.0  4.0  3.0  7.0
2  1.0  7.0  7.0  9.0  3.0
3  4.0  4.0  1.0  3.0  1.0
4  7.0  5.0  4.0  1.0  2.0
5  1.0  6.0  7.0  6.0  3.0
6  7.0  1.0  1.0  5.0  9.0
7  1.0  2.0  4.0  7.0  7.0
8  4.0  3.0  7.0  2.0  5.0

In [33]:
ddef.rank(pct = True)

A         B         C        分数        年龄
0  0.555556  1.000000  0.222222  0.888889  0.611111
1  0.888889  0.888889  0.555556  0.388889  0.833333
2  0.222222  0.777778  0.888889  1.000000  0.388889
3  0.555556  0.444444  0.222222  0.388889  0.111111
4  0.888889  0.555556  0.555556  0.111111  0.222222
5  0.222222  0.666667  0.888889  0.666667  0.388889
6  0.888889  0.111111  0.222222  0.555556  1.000000
7  0.222222  0.222222  0.555556  0.777778  0.833333
8  0.555556  0.333333  0.888889  0.222222  0.611111

In [34]:
ddef

A   B   C   分数  年龄
0  人工智能  甲班  张三   99  21
1   大数据  乙班  李四   80  22
2    h5  丙班  王五  100  20
3  人工智能  A班  张三   80  18
4   大数据  B班  李四   69  19
5    h5  C班  王五   92  20
6   大数据  1班  张三   88  23
7    h5  2班  李四   98  22
8  人工智能  3班  王五   76  21

In [35]:
#通过'A'列分组，然后对分数列进行排序(method = 'dense')表示紧密的排序
ddef.groupby('A').分数.rank(method = 'dense')

0    3.0
1    2.0
2    3.0
3    2.0
4    1.0
5    1.0
6    3.0
7    2.0
8    1.0
Name: 分数, dtype: float64

In [36]:
#通过'A'列进行分组，然后逐步相加
ddef.groupby('A').cumsum()

分数  年龄
0   99  21
1   80  22
2  100  20
3  179  39
4  149  41
5  192  40
6  237  64
7  290  62
8  255  60

In [37]:
#通过'A'列进行分组，然后逐步求最大值
ddef.groupby('A').cummax()

分数  年龄
0   99  21
1   80  22
2  100  20
3   99  21
4   80  22
5  100  20
6   88  23
7  100  22
8   99  21

In [38]:
df = pd.DataFrame({'name':['Alice','Bob','Mallory','Mallory','Bob','Mallory'],
                   'city':['Seat','Seat','Portl','Seat','Seat','Portl'],
                  'val':[4,3,3,np.nan,np.nan,4]})

In [39]:
df

name   city  val
0    Alice   Seat  4.0
1      Bob   Seat  3.0
2  Mallory  Portl  3.0
3  Mallory   Seat  NaN
4      Bob   Seat  NaN
5  Mallory  Portl  4.0

In [40]:
df.groupby(['name','city']).size().reset_index(name = 'size')

name   city  size
0    Alice   Seat     1
1      Bob   Seat     2
2  Mallory  Portl     2
3  Mallory   Seat     1

In [41]:
#通过'name'列进行分组，然后求每个组的元素个数
df.groupby('name').size()

name
Alice      1
Bob        2
Mallory    3
dtype: int64

In [42]:
#通过'name'列进行分组，然后计算每一列的元素个数(不包括NaN值)
df.groupby('name').count()

city  val
name              
Alice       1    1
Bob         2    1
Mallory     3    2

In [43]:
#通过'name'，'city'列进行分组，然后计算每个分组的元素个数
df.groupby(['name','city']).size()

name     city 
Alice    Seat     1
Bob      Seat     2
Mallory  Portl    2
         Seat     1
dtype: int64

In [44]:
#通过'A'列进行分组，然后逐步相乘
ddef.groupby('A').cumprod()

分数    年龄
0      99    21
1      80    22
2     100    20
3    7920   378
4    5520   418
5    9200   400
6  485760  9614
7  901600  8800
8  601920  7938

In [45]:
#通过'name'，'city'进行分组(且作为索引值)，然后对'val'列进行计算个数(不包括NaN值)
df.groupby(['name','city'],as_index = True)['val'].count()

name     city 
Alice    Seat     1
Bob      Seat     1
Mallory  Portl    2
         Seat     0
Name: val, dtype: int64

In [46]:
#通过'name'，'city'进行分组，然后求出每个分组的元素个数(包括NaN值)
df.groupby(['name','city']).size()

name     city 
Alice    Seat     1
Bob      Seat     2
Mallory  Portl    2
         Seat     1
dtype: int64

In [47]:
df = pd.DataFrame({'a':[5,2,3],'b':[4,5,6],
                  'c':[7,2,4]})

In [48]:
df

a  b  c
0  5  4  7
1  2  5  2
2  3  6  4

In [49]:
df.sort_values('a',ascending = False)

a  b  c
0  5  4  7
2  3  6  4
1  2  5  2

In [50]:
df=pd.DataFrame(np.random.randn(6,6),columns=list('ABCDEF'))

In [51]:
df

A         B         C         D         E         F
0 -0.224642  0.764927 -3.279773  1.379954 -1.102928 -1.305566
1 -0.294486  0.183716  1.759811  0.531697 -0.004638 -1.082883
2  0.950613  0.194703 -0.224783 -0.561496  0.425805  1.145316
3 -1.464562  0.082576 -0.327618 -1.172920  0.916277  0.171088
4  0.255540 -0.302076  1.153179 -1.136519 -0.256022  1.540506
5  0.035291  1.760621 -0.781146  0.608015  0.469301  0.360692

In [52]:
df.max(axis = 0) - df.min(axis = 0)

A    2.415175
B    2.062697
C    5.039584
D    2.552875
E    2.019205
F    2.846072
dtype: float64

In [53]:
df = pd.DataFrame({'A':[1,1,2,2],
                   'B':[1,2,3,4],
                  'C':np.random.randn(4)})

In [54]:
df

A  B         C
0  1  1 -0.173382
1  1  2 -0.053619
2  2  3  2.097784
3  2  4 -0.898629

In [55]:
df.groupby('A').agg('min')

B         C
A             
1  1 -0.173382
2  3 -0.898629

In [56]:
df.groupby('A').size()

A
1    2
2    2
dtype: int64

In [57]:
df.groupby('A').agg(['min','max'])

B             C          
  min max       min       max
A                            
1   1   2 -0.173382 -0.053619
2   3   4 -0.898629  2.097784

In [58]:
df.groupby('A').B.agg(['min','max'])

min  max
A          
1    1    2
2    3    4

In [59]:
df.groupby('A').agg({'B':['min','max'],'C':'sum'})

B             C
  min max       sum
A                  
1   1   2 -0.227001
2   3   4  1.199155

In [60]:
df = pd.DataFrame([[4,9],]*3,columns = ['A','B'])

In [61]:
df

A  B
0  4  9
1  4  9
2  4  9

In [62]:
df.apply(np.sqrt)

A    B
0  2.0  3.0
1  2.0  3.0
2  2.0  3.0

In [63]:
df.apply(np.sum)

A    12
B    27
dtype: int64

In [64]:
df.apply(np.sum,axis=1)

0    13
1    13
2    13
dtype: int64

In [65]:
df.apply(lambda x:[1,2],axis=1)

0    [1, 2]
1    [1, 2]
2    [1, 2]
dtype: object

In [66]:
df

A  B
0  4  9
1  4  9
2  4  9

In [67]:
df.apply(lambda x:[1,2],axis=1,result_type = 'expand')

0  1
0  1  2
1  1  2
2  1  2

In [68]:
df.apply(lambda x:pd.Series([1,2],index = ['foo','bar']),axis=1)

foo  bar
0    1    2
1    1    2
2    1    2

In [69]:
df.apply(lambda x:[1,2],axis=1,result_type = 'broadcast')

A  B
0  1  2
1  1  2
2  1  2

In [70]:
df = pd.DataFrame({"foo": ['one', 'one', 'two', 'two'],
...                    "bar": ['A', 'A', 'B', 'C'],
...                    "baz": [1, 2, 3, 4]})

In [71]:
df

foo bar  baz
0  one   A    1
1  one   A    2
2  two   B    3
3  two   C    4

In [72]:
#df.pivot(index = 'foo',columns = 'bar',values = 'baz')

In [73]:
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
...                    'B': {0: 1, 1: 3, 2: 5},
...                    'C': {0: 2, 1: 4, 2: 6}})

In [74]:
df

A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [75]:
df.melt(id_vars = ['A'],value_vars = ['B'])

A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [76]:
df.melt()

variable value
0        A     a
1        A     b
2        A     c
3        B     1
4        B     3
5        B     5
6        C     2
7        C     4
8        C     6

In [77]:
pd.qcut(range(5),3,labels = ['good','medium','bad'])

[good, good, medium, bad, bad]
Categories (3, object): [good < medium < bad]

In [78]:
df = pd.DataFrame({'key1':['a','a','b','b','a'],
                  'key2':['one','two','one','two','one'],
                  'data1':np.random.randn(5),
                  'data2':np.random.randn(5)})

In [79]:
df

key1 key2     data1     data2
0    a  one  0.263881 -0.078196
1    a  two  2.133718 -0.251349
2    b  one  0.259481 -1.090944
3    b  two  1.266282  0.141874
4    a  one -1.730678  0.034467

In [80]:
#通过'key1'列进行分组，然后应用于'data1'列
gr = df['data1'].groupby(df['key1'])

In [81]:
gr    #是一个GroupBy对象，没有进行任何计算

In [82]:
gr.mean()   #计算分组平均值

key1
a    0.222307
b    0.762881
Name: data1, dtype: float64

In [83]:
#通过'key1','key2'列进行分组，然后计算data1列的平均值
means = df.groupby(['key1','key2']).data1.mean()

In [84]:
means

key1  key2
a     one    -0.733398
      two     2.133718
b     one     0.259481
      two     1.266282
Name: data1, dtype: float64

In [85]:
means.unstack()

key2       one       two
key1                    
a    -0.733398  2.133718
b     0.259481  1.266282

In [86]:
states = np.array(['Ohio','California','California',
                  'Ohio','Ohio'])

In [87]:
years = np.array([2005,2005,2006,2005,2006])

In [88]:
df

key1 key2     data1     data2
0    a  one  0.263881 -0.078196
1    a  two  2.133718 -0.251349
2    b  one  0.259481 -1.090944
3    b  two  1.266282  0.141874
4    a  one -1.730678  0.034467

In [89]:
df['data1'].groupby([states,years]).mean()

California  2005    2.133718
            2006    0.259481
Ohio        2005    0.765081
            2006   -1.730678
Name: data1, dtype: float64

In [90]:
df.groupby('key1').mean()

data1     data2
key1                    
a     0.222307 -0.098359
b     0.762881 -0.474535

In [91]:
mask = np.ones(9)

In [92]:
mask

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [93]:
mask[4] = 0

In [94]:
np.convolve?

In [95]:
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [96]:
np.convolve([1,2,3],[0,1,0.5], 'same')

array([1. , 2.5, 4. ])

In [97]:
np.convolve([1,2,3],[0,1,0.5], 'valid')

array([2.5])

In [98]:
a = [1,2]

In [99]:
b = [1,2]

In [100]:
np.convolve(a,b)

array([1, 4, 4])

In [101]:
#a*b[0]得到[1,2]
#a*b[1]得到[0,2,4]
#注意，此处根据b的索引进行0的补充，然后对应位置进行相加

In [103]:
mask = np.ones(9)

In [104]:
mask[4] = 0

In [105]:
mask

array([1., 1., 1., 1., 0., 1., 1., 1., 1.])