In [4]:
import numpy as np

In [5]:
list1 = (1,2,3)

In [6]:
a=np.array(list1)

In [7]:
a

array([1, 2, 3])

In [8]:
a.ndim #数组的维度

1

In [9]:
a.shape

(3,)

In [10]:
a.dtype

dtype('int32')

In [11]:
a.size

3

In [24]:
a.itemsize

4

# 一级标题

## 二级标题

**黑体**

fdafdafdf
> 学而时习之,不亦说乎?

In [29]:
b = np.eye(5)

In [30]:
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
c = np.eye(3,4)

In [32]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [33]:
a

array([1, 2, 3])

In [34]:
a +=2

In [35]:
a

array([3, 4, 5])

In [47]:
b = np.random.random([2,3])

In [48]:
b

array([[0.18440977, 0.53885787, 0.2094421 ],
       [0.84003258, 0.53002237, 0.17871745]])

In [49]:
a = np.ones((2,3), dtype=int)

In [50]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
a +=b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [52]:
b+=a

In [53]:
b

array([[1.18440977, 1.53885787, 1.2094421 ],
       [1.84003258, 1.53002237, 1.17871745]])

In [54]:
2**3

8

In [55]:
import math

In [60]:
math.exp(3)

20.085536923187668

In [63]:
b.sum()

8.481482139033261

In [5]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [13]:
b = np.arange(12).reshape(3,4)

In [14]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [16]:
b.sum(axis=1)

array([ 6, 22, 38])

In [17]:
b = np.arange(24).reshape(2,3,4)

In [18]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
b.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [21]:
b.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [22]:
b.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [25]:
a = np.arange(8).reshape(2,4)


In [26]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
a.sum(axis=0)

array([ 4,  6,  8, 10])

In [28]:
b = np.arange(12).reshape(3,4)

In [29]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [36]:
B = np.arange(4)

In [37]:
B

array([0, 1, 2, 3])

In [38]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [39]:
B

array([0, 1, 2, 3])

In [40]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [41]:
C = np.array([2., -1., 4.,3.2])

In [42]:
np.add(B,C)

array([2. , 0. , 6. , 6.2])

In [43]:
np.add(C,B)

array([2. , 0. , 6. , 6.2])

In [44]:
a = np.arange(10)**3

In [45]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [46]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [47]:
a[:6:2]

array([ 0,  8, 64], dtype=int32)

In [48]:
a[:6:2]= -1000

In [49]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [50]:
a[ : :-1] 

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [55]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [56]:
for i in a:
    print(i)

-1000
1
-1000
27
-1000
125
216
343
512
729


In [57]:
def f(x,y):
    return 10*x+y

In [58]:
b = np.fromfunction(f,(5,4),dtype=int)

In [59]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [60]:
b[2,3]

23

In [61]:
b[0:5, 1] 

array([ 1, 11, 21, 31, 41])

In [62]:
b[0:6, 1] 

array([ 1, 11, 21, 31, 41])

In [64]:
# b[6,7]

In [65]:
b[1]

array([10, 11, 12, 13])

In [66]:
b[ : ,1] 

array([ 1, 11, 21, 31, 41])

In [67]:
b[1:3, : ] 

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [68]:
b[1:3, 1:2 ] 

array([[11],
       [21]])

In [69]:
b[2]

array([20, 21, 22, 23])

In [71]:
b[:,2]

array([ 2, 12, 22, 32, 42])

In [74]:
b[2,...]

array([20, 21, 22, 23])

In [76]:
b[2,:]

array([20, 21, 22, 23])

In [75]:
b[...,2]

array([ 2, 12, 22, 32, 42])

In [77]:
b[:,2]

array([ 2, 12, 22, 32, 42])

In [78]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
               [110,112,113]]])

In [79]:
c[:,1,:]

array([[ 10,  12,  13],
       [110, 112, 113]])

In [80]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [81]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [86]:
a=np.arange(20).reshape(2,2,5)

In [87]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [88]:
for element in a.flat:
     print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
