## 回顾

In [1]:
import numpy as np

遍历array,得到元素

In [2]:
a  = np.arange(12).reshape(3,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
for i in a.flat:
    print(i,end=' ,')

0 ,1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,11 ,

轴axis操作

In [9]:
a.sum()

66

In [10]:
a.sum(axis=0)

array([12, 15, 18, 21])

切片操作

In [12]:
a[1,1:3]

array([5, 6])

In [13]:
a[1,:]

array([4, 5, 6, 7])

索引

In [14]:
a[1,...]

array([4, 5, 6, 7])

In [15]:
a[1]

array([4, 5, 6, 7])

数组a和b,  a += b  和 np.add(a,b) 这两种操作有何异同?

# 新的开始

In [16]:
import math

In [17]:
math.floor(3.1)

3

In [18]:
math.floor(3.9)

3

In [19]:
math.floor(-3.1)

-4

In [20]:
math.floor(-3.9)

-4

In [21]:
math.ceil(3.1)

4

In [22]:
math.ceil(-3.1)

-3

In [27]:
round(3.6)

4

In [28]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [29]:
round(3.4)

3

In [30]:
a = np.floor(10*np.random.random((3,4)))

In [31]:
a

array([[1., 9., 9., 1.],
       [5., 7., 8., 5.],
       [7., 5., 8., 8.]])

In [32]:
a.dtype

dtype('float64')

In [33]:
a.ravel()

array([1., 9., 9., 1., 5., 7., 8., 5., 7., 5., 8., 8.])

In [34]:
a

array([[1., 9., 9., 1.],
       [5., 7., 8., 5.],
       [7., 5., 8., 8.]])

In [35]:
a.reshape(2,6)

array([[1., 9., 9., 1., 5., 7.],
       [8., 5., 7., 5., 8., 8.]])

In [36]:
a

array([[1., 9., 9., 1.],
       [5., 7., 8., 5.],
       [7., 5., 8., 8.]])

In [37]:
a.reshape(4,-1)

array([[1., 9., 9.],
       [1., 5., 7.],
       [8., 5., 7.],
       [5., 8., 8.]])

In [38]:
a.T

array([[1., 5., 7.],
       [9., 7., 5.],
       [9., 8., 8.],
       [1., 5., 8.]])

In [39]:
a

array([[1., 9., 9., 1.],
       [5., 7., 8., 5.],
       [7., 5., 8., 8.]])

In [40]:
a.T.shape

(4, 3)

In [41]:
a.resize(2,6)

In [42]:
a

array([[1., 9., 9., 1., 5., 7.],
       [8., 5., 7., 5., 8., 8.]])

In [46]:
b=np.arange(13).reshape(3,-1)

ValueError: cannot reshape array of size 13 into shape (3,newaxis)

In [47]:
a = np.floor(10*np.random.random((2,2)))

In [48]:
b = np.floor(10*np.random.random((2,2)))

In [49]:
np.vstack((a,b))

array([[3., 1.],
       [4., 4.],
       [6., 3.],
       [4., 9.]])

In [50]:
np.hstack((a,b))

array([[3., 1., 6., 3.],
       [4., 4., 4., 9.]])

In [51]:
a

array([[3., 1.],
       [4., 4.]])

In [52]:
b

array([[6., 3.],
       [4., 9.]])

In [53]:
from numpy import newaxis

In [54]:
np.column_stack((a,b))

array([[3., 1., 6., 3.],
       [4., 4., 4., 9.]])

In [70]:
a = np.array([4.,2.])

In [71]:
b = np.array([3.,8.])

In [72]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [73]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [74]:
a

array([4., 2.])

In [75]:
a[:,newaxis] 

array([[4.],
       [2.]])

In [76]:
b

array([3., 8.])

In [79]:
b[:,newaxis]

array([[3.],
       [8.]])

In [77]:
a

array([4., 2.])

In [78]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [80]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [82]:
np.row_stack((a,b)) # vstack

array([[4., 2.],
       [3., 8.]])

In [83]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [85]:
help(np.c_)

Help on CClass in module numpy.lib.index_tricks object:

class CClass(AxisConcatenator)
 |  Translates slice objects to concatenation along the second axis.
 |  
 |  This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
 |  useful because of its common occurrence. In particular, arrays will be
 |  stacked along their last axis after being upgraded to at least 2-D with
 |  1's post-pended to the shape (column vectors made out of 1-D arrays).
 |  
 |  See Also
 |  --------
 |  column_stack : Stack 1-D arrays as columns into a 2-D array.
 |  r_ : For more detailed documentation.
 |  
 |  Examples
 |  --------
 |  >>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
 |  array([[1, 4],
 |         [2, 5],
 |         [3, 6]])
 |  >>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
 |  array([[1, 2, 3, 0, 0, 4, 5, 6]])
 |  
 |  Method resolution order:
 |      CClass
 |      AxisConcatenator
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |    

In [89]:
np.c_[1:4,2:5,1:4]

array([[1, 2, 1],
       [2, 3, 2],
       [3, 4, 3]])

In [90]:
a = np.floor(10*np.random.random((2,12)))

In [91]:
a

array([[4., 1., 5., 7., 5., 0., 9., 8., 1., 8., 9., 6.],
       [0., 1., 3., 7., 2., 9., 3., 3., 5., 0., 3., 3.]])

In [92]:
np.hsplit(a,3)

[array([[4., 1., 5., 7.],
        [0., 1., 3., 7.]]), array([[5., 0., 9., 8.],
        [2., 9., 3., 3.]]), array([[1., 8., 9., 6.],
        [5., 0., 3., 3.]])]

In [94]:
a

array([[4., 1., 5., 7., 5., 0., 9., 8., 1., 8., 9., 6.],
       [0., 1., 3., 7., 2., 9., 3., 3., 5., 0., 3., 3.]])

In [93]:
np.hsplit(a,(3,4))

[array([[4., 1., 5.],
        [0., 1., 3.]]), array([[7.],
        [7.]]), array([[5., 0., 9., 8., 1., 8., 9., 6.],
        [2., 9., 3., 3., 5., 0., 3., 3.]])]

In [96]:
list1 = np.hsplit(a,(3,5))

In [97]:
type(list1)

list

In [98]:
list1[2]

array([[0., 9., 8., 1., 8., 9., 6.],
       [9., 3., 3., 5., 0., 3., 3.]])

In [100]:
a.resize((6,4))

In [101]:
a

array([[4., 1., 5., 7.],
       [5., 0., 9., 8.],
       [1., 8., 9., 6.],
       [0., 1., 3., 7.],
       [2., 9., 3., 3.],
       [5., 0., 3., 3.]])

In [102]:
np.vsplit(a,2)

[array([[4., 1., 5., 7.],
        [5., 0., 9., 8.],
        [1., 8., 9., 6.]]), array([[0., 1., 3., 7.],
        [2., 9., 3., 3.],
        [5., 0., 3., 3.]])]

In [103]:
np.vsplit(a,(2,3))

[array([[4., 1., 5., 7.],
        [5., 0., 9., 8.]]), array([[1., 8., 9., 6.]]), array([[0., 1., 3., 7.],
        [2., 9., 3., 3.],
        [5., 0., 3., 3.]])]

# 复制还是查看?

根本没复制!

先来一个原生的copy

In [121]:
a = [1,2,3]
b = [a,4,5]
c = b
import copy

d =copy.deepcopy(b)
print('d的值:',d)
print('c的值是:',c)
a[1] = 100
print('-->c的值是:',c)
print('-->d的值是:',d)


d的值: [[1, 2, 3], 4, 5]
c的值是: [[1, 2, 3], 4, 5]
-->c的值是: [[1, 100, 3], 4, 5]
-->d的值是: [[1, 2, 3], 4, 5]


In [117]:
b

[[1, 2], 4, 5]

In [107]:
c = b

In [108]:
c

[[1, 2, 3], 4, 5]

In [109]:
c == b

True

In [110]:
c is b

True

In [112]:
a = [1,2]

In [113]:
c

[[1, 2, 3], 4, 5]

In [114]:
b

[[1, 2, 3], 4, 5]

In [122]:
a = np.arange(12)

In [123]:
b = a

In [124]:
b is a

True

In [125]:
b.shape = 3,4

In [126]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
c = a.view()

In [128]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
a is c

False

In [130]:
a == c

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [131]:
c.base is a

True

In [132]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [133]:
type(c.flags)

numpy.flagsobj

In [134]:
c.flags.owndata

False

In [136]:
c.flags.aligned

True

In [137]:
c.shape = 2,6 

In [138]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [139]:
c[0,4] = 1234

In [142]:
c[1,0] = 100

In [143]:
a

array([[   0,    1,    2,    3],
       [1234,    5,  100,    7],
       [   8,    9,   10,   11]])

In [144]:
s = a[ : , 1:3]

In [145]:
s

array([[  1,   2],
       [  5, 100],
       [  9,  10]])

In [146]:
s[:] = 10

In [147]:
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [148]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [149]:
d = a.copy()

In [150]:
d

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [151]:
d is a

False

In [152]:
d[0,0] = 200

In [153]:
d

array([[ 200,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [154]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

# 下午

In [155]:
a = np.arange(12)**2 

In [156]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [157]:
i = np.array( [ 1,1,3,8,5 ] )

In [158]:
i

array([1, 1, 3, 8, 5])

In [159]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [160]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )

In [161]:
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [162]:
palette = np.array( [ [0,0,0],                # black
                       [255,0,0],              # red
                       [0,255,0],              # green
                       [0,0,255],              # blue
                       [255,255,255] ] )       # white

In [163]:
palette

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])

In [164]:
image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
                     [ 0, 3, 4, 0 ]  ] )

In [165]:
image

array([[0, 1, 2, 0],
       [0, 3, 4, 0]])

In [166]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

** 多维数组索引**

In [167]:
a = np.arange(12).reshape(3,4)

In [169]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
i = np.array( [ [0,1],                        # indices for the first dim of a
                 [1,2] ] )

In [177]:
j = np.array( [ [2,1],                        # indices for the second dim
                 [3,3] ] )

In [178]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [179]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [180]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [182]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
j

array([[2, 1],
       [3, 3]])

In [181]:
a[:,j] 

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [184]:
l = [i,j]

In [187]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [185]:
l

[array([[0, 1],
        [1, 2]]), array([[2, 1],
        [3, 3]])]

In [186]:
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [188]:
s = np.array( [i,j] )

In [189]:
s

array([[[0, 1],
        [1, 2]],

       [[2, 1],
        [3, 3]]])

In [190]:
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [191]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [192]:
tuple(s)

(array([[0, 1],
        [1, 2]]), array([[2, 1],
        [3, 3]]))

## 时间相关

In [193]:
time = np.linspace(20, 145, 5)

In [194]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [195]:
data = np.sin(np.arange(20)).reshape(5,4)      # 4 time-dependent serie

In [196]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [197]:
ind = data.argmax(axis=0)                  # index of the maxima for each series

In [198]:
ind

array([2, 0, 3, 1], dtype=int64)

In [200]:
help(data.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [201]:
max_value = data.max(axis=0)

In [202]:
max_value

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [203]:
max_index = data.argmax(axis=0)

In [204]:
max_index

array([2, 0, 3, 1], dtype=int64)

In [207]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [208]:
ind

array([2, 0, 3, 1], dtype=int64)

In [205]:
time_max = time[ind]

In [206]:
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [210]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [209]:
data_max = data[ind, range(data.shape[1])] # => data[ind[0],0], data[ind[1],1]...

In [214]:
data.shape[1]

4

In [215]:
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [216]:
np.all(data_max == data.max(axis=0))

True

In [217]:
list1= [1,2,3]

In [218]:
all(list1)

True

In [224]:
all([0,None,'',7])

False

In [227]:
any([0,None,'',7])

True

In [228]:
np.all([[True,False],[True,True]])

False

In [229]:
np.all([np.nan,2])

True

In [230]:
np.all([0,1])

False

In [231]:
np.all([2,1])

True

In [232]:
data.max(axis=0)

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [233]:
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [234]:
a = np.arange(5)

In [235]:
a

array([0, 1, 2, 3, 4])

In [236]:
a[[1,3,4]] = 0

In [237]:
a

array([0, 0, 2, 0, 0])

In [248]:
a = np.arange(5)

In [249]:
a

array([0, 1, 2, 3, 4])

In [268]:
a[[0,1,2]]=[100,200,300]

In [269]:
a

array([100, 200, 300,   3,   4])

In [270]:
a[[0,0,2]]=[100,200,300]

In [271]:
a

array([200, 200, 300,   3,   4])

In [284]:
a = np.arange(5)

In [285]:
a

array([0, 1, 2, 3, 4])

In [286]:
a[[0,0,2]]+=1

In [287]:
a

array([1, 1, 3, 3, 4])