In [1]:
import numpy as np

In [3]:
a = np.array([[[1,2,3,0],[3,4,5,2]]])

In [4]:
a

array([[[1, 2, 3, 0],
        [3, 4, 5, 2]]])

In [5]:
a.shape

(1, 2, 4)

In [6]:
a.T

array([[[1],
        [3]],

       [[2],
        [4]],

       [[3],
        [5]],

       [[0],
        [2]]])

In [7]:
a.T.shape

(4, 2, 1)

In [8]:
a.transpose()   #a.transpose可以指定到底要怎么变换：比如原来是 [1,2,4]， 
#可以指定转变的方式 [0,2,1]， 这个 [0,2,1] 的意思是 第一个维度不变，后两个维度交换
# 那么形状就变成了 [1,4,2]

array([[[1],
        [3]],

       [[2],
        [4]],

       [[3],
        [5]],

       [[0],
        [2]]])

In [11]:
a

array([[[1, 2, 3, 0],
        [3, 4, 5, 2]]])

In [10]:
a.transpose([0,1,2])

array([[[1, 2, 3, 0],
        [3, 4, 5, 2]]])

In [ ]:
# a.transpose([1,0,2]),原矩阵index(1,2,3)-->变换后矩阵(2,1,3)

In [12]:
a.transpose([2,1,0])

array([[[1],
        [3]],

       [[2],
        [4]],

       [[3],
        [5]],

       [[0],
        [2]]])

In [13]:
a.transpose([0,2,1])

array([[[1, 3],
        [2, 4],
        [3, 5],
        [0, 2]]])

In [14]:
a

array([[[1, 2, 3, 0],
        [3, 4, 5, 2]]])

In [ ]:
2 在a 中index 是(0,0,1),  转换完成后,新的坐标点为(0,1,0)

In [16]:
a = np.arange(9).reshape(3,3)

In [17]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
a = np.array([[ 10.,  14.,  18.],
       [ 14.,  20.,  26.],
       [ 18.,  26.,  34.]])

In [21]:
a

array([[10., 14., 18.],
       [14., 20., 26.],
       [18., 26., 34.]])

In [22]:
np.linalg.inv(a)

array([[ 2.50199979e+14, -5.00399959e+14,  2.50199979e+14],
       [-5.00399959e+14,  1.00079992e+15, -5.00399959e+14],
       [ 2.50199979e+14, -5.00399959e+14,  2.50199979e+14]])

In [23]:
# 求是否相同
# Returns True if two arrays are element-wise equal within a tolerance : default 1e-08
np.allclose?

In [25]:
from numpy.linalg import inv

a = np.array([[1., 2.], [3., 4.]])

In [26]:
ainv = inv(a)

In [27]:
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
# here is to check if np.dot(a, ainv) equals to I matrix
np.allclose(np.dot(a, ainv), np.eye(2))

True

In [29]:
np.dot(a, ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [30]:
from numpy.linalg import *

In [31]:
np.linalg.eig(np.dot(a.T,a))

(array([ 0.13393125, 29.86606875]), array([[-0.81741556, -0.57604844],
        [ 0.57604844, -0.81741556]]))

In [32]:
a = np.array([[1., 2.], [3., 4.]])

In [34]:
np.trace(a)

5.0

In [35]:
help(np.trace)

Help on function trace in module numpy.core.fromnumeric:

trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
    Return the sum along diagonals of the array.
    
    If `a` is 2-D, the sum along its diagonal with the given offset
    is returned, i.e., the sum of elements ``a[i,i+offset]`` for all i.
    
    If `a` has more than two dimensions, then the axes specified by axis1 and
    axis2 are used to determine the 2-D sub-arrays whose traces are returned.
    The shape of the resulting array is the same as that of `a` with `axis1`
    and `axis2` removed.
    
    Parameters
    ----------
    a : array_like
        Input array, from which the diagonals are taken.
    offset : int, optional
        Offset of the diagonal from the main diagonal. Can be both positive
        and negative. Defaults to 0.
    axis1, axis2 : int, optional
        Axes to be used as the first and second axis of the 2-D sub-arrays
        from which the diagonals should be taken. Defaults are the 

In [36]:
a = np.arange(8).reshape((2,2,2))

In [38]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a.trace()

array([6, 8])

In [39]:
a = np.array([[ 1.,  3.],
       [ 2.,  4.]])

In [40]:
a.swapaxes(0,1) # 0 1轴

array([[1., 2.],
       [3., 4.]])

In [42]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 9]))  # bin 格子,编号0的格子有1个

array([1, 3, 1, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [46]:
b = np.random.randn(10)

In [47]:
b

array([-0.18664997,  0.30191473, -0.02569164, -1.22994604,  1.43874938,
        0.94833823,  0.92129587,  0.39106782,  1.56291381,  0.74807107])

In [48]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

In [54]:
# in1d test values in one array
e = np.array([1,2,3,3,6,4,4,5])

np.in1d([2,4,8],e)

# check if element in the first array appears in the second array

array([ True,  True, False])

In [55]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])