In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(2,3,4)

In [3]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
row_a = a.transpose([0,1,2])

In [5]:
row_a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
change_zero_one_a = a.transpose([1,0,2])

In [7]:
change_zero_one_a

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [8]:
a.shape

(2, 3, 4)

In [9]:
change_zero_one_a.shape

(3, 2, 4)

In [10]:
# a当中index为 (1,2,3)
a[1,2,3]

23

In [12]:
change_zero_one_a[2,1,3]

23