In [1]:
import numpy as np
import pandas as pd

# convolve

In [2]:
n = np.array([1,2,3,4,5])

In [35]:
m = np.array((2,5))

In [36]:
np.convolve(n,m,mode='full')

array([ 2,  9, 16, 23, 30, 25])

# 参数是：full时的运算过程

In [37]:
#n[0]=1,n[1]=2,n[2]=3,n[3]=4,n[4]=5
#m[0]=2,m[1]=5
[
n[0]*m[0],
n[1]*m[0]+n[0]*m[1],
n[2]*m[0]+n[1]*m[1],
n[3]*m[0]+n[2]*m[1],
n[4]*m[0]+n[3]*m[1],
n[4]*m[1]
]

[2, 9, 16, 23, 30, 25]

In [38]:
np.convolve(n,m,mode='same')

array([ 2,  9, 16, 23, 30])

# 参数是：same时的运算过程
## (先删后边)

In [39]:
[
n[0]*m[0],
n[1]*m[0]+n[0]*m[1],
n[2]*m[0]+n[1]*m[1],
n[3]*m[0]+n[2]*m[1],
n[4]*m[0]+n[3]*m[1],
]

[2, 9, 16, 23, 30]

In [40]:
np.convolve(n,m,mode='valid')

array([ 9, 16, 23, 30])

# 参数是：valid时的运算过程

In [41]:
[
n[1]*m[0]+n[0]*m[1],
n[2]*m[0]+n[1]*m[1],
n[3]*m[0]+n[2]*m[1],
n[4]*m[0]+n[3]*m[1],
]

[9, 16, 23, 30]