函数和方法(method)总览
创建数组

arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r , zeros, zeros_like 

转化

astype, atleast 
1d
, atleast 
2d
, atleast 
3d
, mat 

操作

array split, column stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack 

询问

all, any, nonzero, where 

排序

argmax, argmin, argsort, max, min, ptp, searchsorted, sort 

运算

choose, compress, cumprod, cumsum, inner, fill, imag, prod, put, putmask, real, sum 

基本统计

cov, mean, std, var 

基本线性代数

cross, dot, outer, svd, vdot

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int32')

In [7]:
a.dtype.name

'int32'

In [8]:
a.size

15

In [9]:
a.itemsize

4

In [10]:
type(a)

numpy.ndarray

# 创建数组

In [11]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [12]:
c = np.array([1.1,2.1,3.1,4.1,5.1])
c

array([1.1, 2.1, 3.1, 4.1, 5.1])

In [13]:
c.dtype

dtype('float64')

In [14]:
d = np.array([[1,2],[3,4]],dtype=complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
d.dtype

dtype('complex128')

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros((3,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones((3,4),dtype=complex)

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [20]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [22]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [24]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [25]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [26]:
e = np.array([20,30,40,50])
f = np.arange(4)

In [27]:
g = e-f
g

array([20, 29, 38, 47])

In [28]:
f**2

array([0, 1, 4, 9], dtype=int32)

In [29]:
10*np.sin(a)

array([[ 0.        ,  8.41470985,  9.09297427,  1.41120008, -7.56802495],
       [-9.58924275, -2.79415498,  6.56986599,  9.89358247,  4.12118485],
       [-5.44021111, -9.99990207, -5.36572918,  4.20167037,  9.90607356]])

# 基本运算

In [30]:
A = np.array([[1,1],[0,1]])
A

array([[1, 1],
       [0, 1]])

In [31]:
B = np.array([[2,0],[3,4]])
B

array([[2, 0],
       [3, 4]])

In [32]:
A*B

array([[2, 0],
       [0, 4]])

In [33]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [34]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [35]:
np.dot(B,A)

array([[2, 2],
       [3, 7]])

In [36]:
h = np.ones((2,3))
i = np.random.random((2,3))

In [37]:
h*=3
h

array([[3., 3., 3.],
       [3., 3., 3.]])

In [38]:
i+=h
i

array([[3.79262897, 3.50389538, 3.34876753],
       [3.93787345, 3.12392261, 3.69577887]])

In [39]:
h+=i
h

array([[6.79262897, 6.50389538, 6.34876753],
       [6.93787345, 6.12392261, 6.69577887]])

In [40]:
j = np.ones(3,dtype=int)
k = np.linspace(0,np.pi,3)

In [41]:
l = j+k
l

array([1.        , 2.57079633, 4.14159265])

In [42]:
l.dtype

dtype('float64')

In [43]:
m = np.exp(l*1j)
m

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [44]:
d.dtype.name

'complex128'

In [45]:
n = np.random.random((2,3))
n

array([[0.79992337, 0.61544548, 0.77934864],
       [0.12799433, 0.80764848, 0.62408407]])

In [46]:
n.sum()

3.7544443637848426

In [47]:
n.min()

0.1279943258851809

In [48]:
n.max()

0.8076484765958981

In [49]:
o = np.arange(12).reshape(3,4)
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
o.sum(axis=0)

array([12, 15, 18, 21])

In [51]:
o.sum(axis=1)

array([ 6, 22, 38])

In [52]:
o.min(axis=0)

array([0, 1, 2, 3])

In [53]:
o.min(axis=1)

array([0, 4, 8])

In [54]:
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
o.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [56]:
o.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [57]:
C = np.arange(3)
C

array([0, 1, 2])

In [58]:
np.exp(C)

array([1.        , 2.71828183, 7.3890561 ])

In [59]:
np.sqrt(C)

array([0.        , 1.        , 1.41421356])

In [60]:
D = np.array([2.,-1,4.])
D

array([ 2., -1.,  4.])

In [61]:
np.add(C,D)

array([2., 0., 6.])

In [62]:
p = np.arange(10)**3
p

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [63]:
p[2]

8

In [64]:
p[2:5]

array([ 8, 27, 64], dtype=int32)

In [65]:
p[:6:2] = -1000
p

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [66]:
p[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [67]:
for i in p:
    print(i**(1/3),end=',')

nan,1.0,nan,3.0,nan,5.0,5.999999999999999,6.999999999999999,7.999999999999999,8.999999999999998,

C:\Users\28646\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [68]:
def f(x,y):
    return 10*x+y

In [69]:
q = np.fromfunction(f,(5,4))
q

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [70]:
q[2,3]

23.0

In [71]:
q[0:5,1]

array([ 1., 11., 21., 31., 41.])

In [72]:
q[:,1]

array([ 1., 11., 21., 31., 41.])

In [73]:
q[1:3,:]

array([[10., 11., 12., 13.],
       [20., 21., 22., 23.]])

In [74]:
q[-1]

array([40., 41., 42., 43.])

In [75]:
q[1,2,...]

array(12.)

In [76]:
q[...,3]

array([ 3., 13., 23., 33., 43.])

In [77]:
q[4,...]

array([40., 41., 42., 43.])

In [78]:
for row in q:
    print(row)

[0. 1. 2. 3.]
[10. 11. 12. 13.]
[20. 21. 22. 23.]
[30. 31. 32. 33.]
[40. 41. 42. 43.]


In [79]:
for row in q.flat:
    print(row)

0.0
1.0
2.0
3.0
10.0
11.0
12.0
13.0
20.0
21.0
22.0
23.0
30.0
31.0
32.0
33.0
40.0
41.0
42.0
43.0


In [80]:
r = np.floor(10*np.random.random((3,4)))#向下取整
r

array([[6., 4., 7., 2.],
       [9., 0., 7., 1.],
       [3., 5., 6., 8.]])

In [81]:
r.shape

(3, 4)

In [82]:
s = np.ceil(10*np.random.random((3,4)))#向上取整
s

array([[10.,  2.,  5.,  5.],
       [ 6.,  3.,  9.,  6.],
       [ 8.,  1.,  7.,  2.]])

In [83]:
r.ravel()

array([6., 4., 7., 2., 9., 0., 7., 1., 3., 5., 6., 8.])

In [84]:
r.shape = (6,2)
r.transpose()

array([[6., 7., 9., 7., 3., 6.],
       [4., 2., 0., 1., 5., 8.]])

In [85]:
r

array([[6., 4.],
       [7., 2.],
       [9., 0.],
       [7., 1.],
       [3., 5.],
       [6., 8.]])

In [86]:
t = np.floor(10*np.random.random((2,2)))
t

array([[5., 5.],
       [3., 5.]])

In [87]:
u = np.floor(10*np.random.random((2,2)))
u

array([[4., 4.],
       [9., 0.]])

In [88]:
np.vstack((t,u))

array([[5., 5.],
       [3., 5.],
       [4., 4.],
       [9., 0.]])

In [89]:
np.hstack((t,u))

array([[5., 5., 4., 4.],
       [3., 5., 9., 0.]])

In [90]:
np.column_stack((t,u))

array([[5., 5., 4., 4.],
       [3., 5., 9., 0.]])

In [91]:
np.row_stack((t,u))

array([[5., 5.],
       [3., 5.],
       [4., 4.],
       [9., 0.]])

In [92]:
v = np.floor(10*np.random.random((2,12)))
v

array([[1., 4., 9., 9., 8., 3., 8., 5., 2., 5., 1., 4.],
       [8., 0., 3., 0., 1., 9., 3., 8., 9., 6., 9., 9.]])

In [93]:
np.hsplit(v,3)

[array([[1., 4., 9., 9.],
        [8., 0., 3., 0.]]), array([[8., 3., 8., 5.],
        [1., 9., 3., 8.]]), array([[2., 5., 1., 4.],
        [9., 6., 9., 9.]])]

In [94]:
np.vsplit(v,1)

[array([[1., 4., 9., 9., 8., 3., 8., 5., 2., 5., 1., 4.],
        [8., 0., 3., 0., 1., 9., 3., 8., 9., 6., 9., 9.]])]

In [95]:
w = np.arange(12)
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
x = w
x is w

True

In [97]:
x.shape = 3,4

In [98]:
w.shape

(3, 4)

In [99]:
y = w.view()
y is w

False

In [100]:
y.base is w

True

In [101]:
y.shape = 2,6

In [102]:
w.shape

(3, 4)

In [103]:
z = w.copy()
z is w

False

In [104]:
z.base is w

False

In [105]:
z[0,0] = 9999
z

array([[9999,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [106]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])