In [1]:
import numpy as np
import pandas as pd

In [2]:
n1 = np.arange(2,10).reshape(2,4)

In [3]:
n1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [50]:
np.convolve?

In [5]:
n1[0]

array([2, 3, 4, 5])

In [6]:
np.convolve(n1[0],n1[1])

array([ 12,  32,  61, 100,  94,  76,  45])

In [7]:
np.convolve(n1[0],n1[1],'same')

array([ 32,  61, 100,  94])

In [9]:
np.convolve(n1[0],n1[1],'valid')

array([100])

In [48]:
n1[0][1]

3

## a和v长度不相等

In [49]:
np.convolve([1,2,3,4],[0,1,2],)#返回的个数是:(a的长度)+(v的长度)-1

array([ 0,  1,  4,  7, 10,  8])

In [14]:
np.convolve([1,2,3,4],[0,1,2],'valid')#返回的个数是:(长度长的数组)-(长度短的数组)+1

array([4, 7])

In [15]:
np.convolve([1,2,3,4],[0,1,2],'same')#返回的个数:和长度最长的那一个数组长度一样-----但是是在full的基础上从中间往外边扩散

array([ 1,  4,  7, 10])

## a和v长度相等

In [17]:
np.convolve([1,2,3],[0,1,2],'full')

array([0, 1, 4, 7, 6])

In [11]:
np.convolve([1,2,3],[0,1,2],'same')

array([1, 4, 7])

In [12]:
np.convolve([1,2,3],[0,1,2],'valid')

array([4])

In [ ]:
n10_n11_0 = n1[0]*n1[1][0]
n10_n11_0

In [ ]:
n10_n11_1 = n1[0]*n1[1][1]
n10_n11_1

In [ ]:
n10_n11_2 = n1[0]*n1[1][2]
n10_n11_2

In [20]:
np.convolve([1,2,3,4,5],[2,3],'vaid')

array([ 7, 12, 17, 22])

## 可以计算生命游戏存活的个数

In [35]:
np.convolve([1,0,1,0,1,0,1,0],[1,1,1,1,1,1,1,1],'valid')

array([4])

In [36]:
one = [[1,0,1],
      [0,1,1],
      [1,0,0]]

In [40]:
two = np.ones(9)

In [42]:
two[4]=0

In [43]:
two

array([1., 1., 1., 1., 0., 1., 1., 1., 1.])

In [44]:
on1= np.ravel(one)

In [45]:

on1

array([1, 0, 1, 0, 1, 1, 1, 0, 0])

In [47]:
sum(on1*two)

4.0