In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ndarray和DataFrame排序

In [7]:
# s.sort()    改变原数组
# np.sort(s)  不改变原数组

In [8]:
s = np.array([1,3,1,2,1,5,1,2])
s.sort()
s

array([1, 1, 1, 1, 2, 2, 3, 5])

In [9]:
s1 = np.array([1,3,1,2,1,5,1,2])
np.sort(s1)

array([1, 1, 1, 1, 2, 2, 3, 5])

In [10]:
s1

array([1, 3, 1, 2, 1, 5, 1, 2])

In [17]:
# DataFrame排序 sort_index 和 sort_values

In [11]:
df = pd.DataFrame(np.random.randint(0,6,(2,3)))
df

0  1  2
0  5  5  4
1  4  4  1

In [12]:
df.sort_index(ascending = False)

0  1  2
1  4  4  1
0  5  5  4

In [16]:
df.sort_values(by=1)

0  1  2
1  4  4  1
0  5  5  4

# 数组的改变

In [25]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a.copy()

## s.resize(shape) 
### 改变数组的形状 改变了原数组

In [26]:
a.resize((1,9))   
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## s.ravel()
### 把多维数组变成一维数组，原数组不变

In [30]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## s.reshape(shape)
### 改变数组的形状，原数组不变

In [35]:
b.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 拼接数组

In [37]:
# 水平拼接
# np.column_stack((a,b))
# np.hstack((a,b))
# np.c_[a,b]

# Series增加

### s.add(相同长度的列表)
### 对应元素相加

In [49]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [50]:
s.add([1,1,1,1])

0    2
1    3
2    4
3    5
dtype: int64

### s.append(Serise,ignore_index=True)
### 添加Series 

In [52]:
s1 = pd.Series([1,1])

In [53]:
s.append(s1)

0    1
1    2
2    3
3    4
0    1
1    1
dtype: int64

In [54]:
s.append(s1,ignore_index=True)

0    1
1    2
2    3
3    4
4    1
5    1
dtype: int64

In [51]:
help(s.append)

Help on method append in module pandas.core.series:

append(to_append, ignore_index=False, verify_integrity=False) method of pandas.core.series.Series instance
    Concatenate two or more Series.
    
    Parameters
    ----------
    to_append : Series or list/tuple of Series
    ignore_index : boolean, default False
        If True, do not use the index labels.
    
        .. versionadded:: 0.19.0
    
    verify_integrity : boolean, default False
        If True, raise Exception on creating index with duplicates
    
    Notes
    -----
    Iteratively appending to a Series can be more computationally intensive
    than a single concatenate. A better solution is to append values to a
    list and then concatenate the list with the original Series all at
    once.
    
    See also
    --------
    pandas.concat : General function to concatenate DataFrame, Series
        or Panel objects
    
    Returns
    -------
    appended : Series
    
    Examples
    --------
    >>> s1 = p

In [56]:
a.size

9

In [57]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.random.uniform(0,100)

85.87529450844987

# isin()

In [64]:
df2 = pd.DataFrame({'A':[1,1,2,3,4,3]})
df2['E'] = ['one','one','two','three','four','three']
df2

A      E
0  1    one
1  1    one
2  2    two
3  3  three
4  4   four
5  3  three

In [68]:
df2[df2['E'].isin(['two','four'])]

A     E
2  2   two
4  4  four

In [71]:
df2.loc[[2,4]]

A     E
2  2   two
4  4  four

# stack unstack

In [74]:
# 将列标题变为行索引
# 将行索引变为列标题

# df.fillna()
### 将缺失值替换掉

In [80]:
df = pd.DataFrame(np.arange(9).reshape(3,3),
                 index = list('abc'))
df1 = df.reindex(list('abcd'))

In [81]:
df1.fillna(5)

0    1    2
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0
d  5.0  5.0  5.0

In [84]:
df2 = df.reindex(list('abcd'),fill_value=5)
df2

0  1  2
a  0  1  2
b  3  4  5
c  6  7  8
d  5  5  5